### ISSUE TITLE
Add  Configuration file functionality

### ISSUE THREAD

**Issue by FabianCernota** [bio-routing/bio-rd#107]

**Comment by hikhvar** [comment]
Any ideas for the config file Format? Many newer tools use yaml. However, toml is also an interessting format. I oppose to implement a custom format.

**Comment by FabianCernota** [comment]
I would prefer yaml. I think most admins are able to use this.

**Comment by dduenker** [comment]
If you would consider using a library, viper supports yaml and toml: 
https://github.com/spf13/viper

**Comment by FabianCernota** [comment]
See #111
