### ISSUE TITLE
Rename pfxlen field

### ISSUE THREAD

**Issue by corny** [bio-routing/bio-rd#150]
Please rename `pfxlen` into `length`, because `prefix.pfxlen` stutters.

## net/api/net.proto
```
message Prefix {
    IP address = 1;
    uint32 length = 2; // before: pfxlen
}
```

## net/prefix.go
```
type Prefix struct {
	addr   IP
	pfxlen uint8 // better: len or length
}
```

**Comment by ahmedsharif865** [comment]
Is someone still working on this issue?

**Comment by taktv6** [comment]
The suggested change was not implemented yet. Feel free to file a PR.
