### ISSUE TITLE
fix: example netlink was removed in favor of the example device

### ISSUE THREAD

**Issue by cedi** [bio-routing/bio-rd#202]
**Describe the bug**
I've discovered that the example netlink is not longer existing and the functionality is now in the device example

**Expected behavior**
Documentation should be 1:1 with the actual code / examples

**Comment by pviotti** [comment]
![image](https://user-images.githubusercontent.com/1350095/54378266-daab6500-467e-11e9-9a2b-4013f2a46259.png)

**Comment by cedi** [comment]
resolved by merging #203
