### ISSUE TITLE
bio-rd should support IPv4+

### ISSUE THREAD

**Issue by mellowdrifter** [bio-routing/bio-rd#262]
I have it on good authority that IPv4+ is the 'next big thing' 

https://www.ripe.net/ripe/mail/archives/members-discuss/2020-April/003676.html

**Comment by BarbarossaTM** [comment]
Yeah, I hope we are to be included in the upcoming round table so implementational details can be discussed. Until then this issue is postponed.

**Comment by BarbarossaTM** [comment]
We sadly didn't hear anything about the round table, so closing this issue 😂
