### ISSUE TITLE
Version number for pre-releases should have a dot

### ISSUE THREAD

**Issue by vincentbernat** [bio-routing/bio-rd#361]
Currently, Go ecosystem believes the last version is v0.0.3-pre9: see https://pkg.go.dev/github.com/bio-routing/bio-rd@v0.0.3-pre9/protocols/bgp/server?tab=versions. There should be a dot after `pre`: v0.0.3-pre.18. But then, I think that it will be ordered before `pre9`. Maybe just bump to 0.0.4?

**Comment by taktv6** [comment]
Hi Vincent,

good point. I think it's about time to actually start having non pre releases.
Thus I've just release v0.1.0. We'll increment from there from now on.
