### ISSUE TITLE
Allow a user to specify its own logger

### ISSUE THREAD

**Issue by vincentbernat** [bio-routing/bio-rd#362]
When using bio-rd as a library, this is not possible to override the global logrus logger (well it is, as long as you only have one dependency using logrus, but that's not super clean). Instead, each component should use its own logger. `bgp/server.Router` already has its own logger, but it is not user-settable.

I would propose to add a `Logger` field to each structure needed it. It will be set to `log.New()` by default or inherited if it is sensible. As long as the "New" methods don't try to log, this should work good enough. This does not require modifying any signature.

I can do the work if it is deemed acceptable. More complex alternatives would be to define a logging interface to avoid depending on logrus, but I don't need that myself and this is far more work.

**Comment by BarbarossaTM** [comment]
Hey,

having one central place to set up logging to do whatever you please sounds like good idea. I feel we want to stay with `logrus` in any way, so an interface seems to be too involved.

I'd probably name the attribute and potential parameter to the `New()` methods `log` though to stick with the name.

**Comment by vincentbernat** [comment]
Do you prefer to add a `log` parameter to all `New()` method?

**Comment by taktv6** [comment]
Hi Vincent, 

Just discussed this with @BarbarossaTM and we came to the conclusion we would like to have a proxy log package that act's like logrus but isn't necessarily logrus.

Example:
`package log

import "github.com/sirupsen/logrus"

type LoggerI interface {
	Warning(args ...interface{})
}

var logger LoggerI

func init() {
	logger = logrus.New()
}

func SetLogger(l LoggerI) {
	logger = l
}

func Warning(args ...interface{}) {
	logger.Warning(args...)
}
`

That package could live under the utils folder. It would allow a user to replace the default logger when necessary using the SetLogger() function, without the need to pass around a logger object over the whole code base. Once that package is implemented and covers all our logrus use cases we would only need to replace the logrus imports with imports of this new package => Profit.

Let me know what you think about that proposal.

Cheers,
takt

**Comment by vincentbernat** [comment]
This would mean we keep a global logger, but at least it is specific to bio-rd. I have other libraries (like Sarama for Kafka) using the same approach, so it's OK for me. It's also easier. ;-)
