### ISSUE TITLE
Newbie seeking improved README.md with build and test instructions (better than the examples)

### ISSUE THREAD

**Issue by ricky-charlet** [bio-routing/bio-rd#457]
**Describe the feature**
README.md improvement

**Use cases / additional context**
For new people curious about this project (like me), the current README.md leaves me stuck/unable to perceive how to build/test/run this project. Building the examples and testing coverage do currently work. But doing that left me ignorant about how to use/test bio-rd.

Rather than an issue report, it would be far better to have a mail-list for a conversation about assisting a newbie. But I could not find an email group or chat group.

Q. How do I build bio-rd?
Q. How do I run bio-rd?
  (kindof expecting suggestions about docker setup??)

**Comment by ricky-charlet** [comment]
(If there is an email distribution list or chat service where this conversation would be better hosted, please let me know.)

How does one start a routing protocol server and start a cli client and connect them?

**Comment by taktv6** [comment]
Hi, 

I'm really sorry we don't have better docs.
But here are some breadcrumbs for you (that you may want to file into a PR?).

How to build? Basically run "go build".
You've got to do so in one of the folders under cmd/ folder. 
bio-rd is the daemon and bio-rdc is the cli client. Check out the -h option on both to get an idea.

bio-rd has a config file (YAML). The config file format is only documented in source code (https://github.com/bio-routing/bio-rd/blob/master/cmd/bio-rd/config/config.go#L10). So you'll have to read a bit of the code.

Let us know of your success and really feel invited to improve the readme!

**Comment by BarbarossaTM** [comment]
I've tried to go a first step into this direction and prepared an update for the README and some building blocks (pun intended :-)), which should lower the bar of entry a little bit.

https://github.com/bio-routing/bio-rd/pull/459

As stated in the PR, this will need further work and examples, to connect more dots.
